// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129092810_ImplementForbiddenWords")]
    partial class ImplementForbiddenWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Infrastructure.Entities.ForbiddenWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("ForbiddenWords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Word = "python"
                        },
                        new
                        {
                            Id = 2,
                            Word = "javascript"
                        },
                        new
                        {
                            Id = 3,
                            Word = "mvc"
                        });
                });

            modelBuilder.Entity("ProductService.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Name = "Laptop",
                            Price = 3999.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Name = "CSharp Book",
                            Price = 59.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Name = "Wireless Mouse",
                            Price = 129.99m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Name = "Regular Keyboard",
                            Price = 449.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            Name = "T-Shirt",
                            Price = 89.99m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Name = "Monitor 27inch",
                            Price = 1299.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            Name = "Headphones",
                            Price = 299.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            Name = "Webcam HD",
                            Price = 199.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Name = "Cracow University of Technology Campus Guide",
                            Price = 199.99m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Name = "SQL Book",
                            Price = 49.99m,
                            Quantity = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
