// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125172813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            Price = 3999.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Programming Book From Cracow University of Technology",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wireless Mouse",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Regular Keyboard",
                            Price = 449.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "USB-C Cable",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Monitor 27inch",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Headphones",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Webcam HD",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Monitor 24inch",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gaming Laptop",
                            Price = 3999.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
